# Generated by Django 6.0.3 on 2026-03-13 12:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=200, verbose_name='Короткое название')),
                ('full_name', models.CharField(max_length=500, verbose_name='Полное название')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=15, verbose_name='ОГРН')),
                ('legal_address', models.TextField(blank=True, verbose_name='Юридический адрес')),
                ('postal_address', models.TextField(blank=True, verbose_name='Почтовый адрес')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='Банк')),
                ('bik', models.CharField(blank=True, max_length=9, verbose_name='БИК')),
                ('corr_account', models.CharField(blank=True, max_length=20, verbose_name='Корр. счёт')),
                ('settlement_account', models.CharField(blank=True, max_length=20, verbose_name='Расч. счёт')),
                ('director', models.CharField(blank=True, max_length=200, verbose_name='Руководитель')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Юридическое лицо',
                'verbose_name_plural': 'Юридические лица',
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=30, verbose_name='Сокращение')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Автор / кафедра')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cover_color', models.CharField(default='#0f62ae', max_length=7, verbose_name='Цвет обложки')),
                ('cover_emoji', models.CharField(default='📘', max_length=10, verbose_name='Эмодзи обложки')),
                ('cover_bg', models.CharField(blank=True, max_length=200, verbose_name='CSS-градиент обложки')),
                ('test_time_minutes', models.PositiveIntegerField(default=20, verbose_name='Время на тест (мин)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', 'Слушатель'), ('teacher', 'Преподаватель'), ('admin', 'Администратор'), ('superadmin', 'Суперадмин')], default='student', max_length=20, verbose_name='Роль')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CourseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('type', models.CharField(choices=[('online', 'Онлайн-лекция'), ('pdf', 'PDF-материал'), ('practice', 'Практическое занятие'), ('upload', 'Загрузка работы'), ('test', 'Тестирование')], default='online', max_length=10, verbose_name='Тип')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='Роль / тип занятия')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='Ссылка')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата проведения')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Шаг курса',
                'verbose_name_plural': 'Шаги курсов',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snils', models.CharField(max_length=14, unique=True, verbose_name='СНИЛС')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('last_name_en', models.CharField(blank=True, max_length=100, verbose_name='Фамилия (англ)')),
                ('first_name_en', models.CharField(blank=True, max_length=100, verbose_name='Имя (англ)')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                ('workplace', models.CharField(blank=True, max_length=200, verbose_name='Место работы')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('code', models.CharField(blank=True, help_text='Используется как пароль для входа в систему', max_length=6, verbose_name='Код доступа (6 цифр)')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL, verbose_name='Учётная запись')),
            ],
            options={
                'verbose_name': 'Физическое лицо',
                'verbose_name_plural': 'Физические лица',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата заявки')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма')),
                ('payer', models.CharField(blank=True, max_length=200, verbose_name='Плательщик')),
                ('partner', models.CharField(blank=True, max_length=100, verbose_name='Сетевой партнёр')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Автор')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='courses.person', verbose_name='Слушатель')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True, verbose_name='Дата назначения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='Курс')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.person', verbose_name='Слушатель')),
            ],
            options={
                'verbose_name': 'Зачисление',
                'verbose_name_plural': 'Зачисления',
                'ordering': ['-assigned_date'],
                'unique_together': {('person', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Категория')),
                ('prog_type', models.CharField(blank=True, max_length=50, verbose_name='Тип')),
                ('code', models.CharField(max_length=200, verbose_name='Код/название программы')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
                ('discount', models.CharField(blank=True, max_length=50, verbose_name='Скидка')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='К оплате')),
                ('cert_number', models.CharField(blank=True, max_length=100, verbose_name='№ сертификата')),
                ('reg_number', models.CharField(blank=True, max_length=100, verbose_name='Рег. номер')),
                ('grade', models.CharField(blank=True, max_length=50, verbose_name='Оценка')),
                ('issue_status', models.CharField(choices=[('da', 'На выдачу'), ('ne', 'Не выдавать'), ('otm', 'Отменён')], default='ne', max_length=3, verbose_name='Статус выдачи')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='courses.order', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Подготовка',
                'verbose_name_plural': 'Подготовки',
                'ordering': ['date_start'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('type', models.CharField(choices=[('single', 'Один ответ'), ('multi', 'Несколько ответов'), ('order', 'Последовательность'), ('match', 'Сопоставление')], default='single', max_length=10, verbose_name='Тип')),
                ('points', models.PositiveIntegerField(default=2, verbose_name='Баллы')),
                ('weight', models.PositiveIntegerField(default=1, verbose_name='Вес')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='URL изображения')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Подпись к рисунку')),
                ('description', models.TextField(blank=True, verbose_name='Описание / подсказка')),
                ('instruction', models.TextField(default='Выберите <strong>один правильный ответ</strong>.', verbose_name='Инструкция')),
                ('answers', models.JSONField(help_text='Массив строк: ["ответ 1","ответ 2",...]', verbose_name='Варианты ответов')),
                ('correct', models.JSONField(help_text='Массив индексов правильных ответов: [0,2]', verbose_name='Правильные ответы')),
                ('terms', models.JSONField(blank=True, help_text='Массив строк для сопоставления', null=True, verbose_name='Понятия (для match)')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.coursestep', verbose_name='Шаг (тест)')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['step', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StepCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_file', models.FileField(blank=True, upload_to='uploads/steps/', verbose_name='Загруженный файл')),
                ('test_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Результат теста (%)')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_steps', to='courses.enrollment', verbose_name='Зачисление')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Проставил зачёт')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='courses.coursestep', verbose_name='Шаг')),
            ],
            options={
                'verbose_name': 'Прохождение шага',
                'verbose_name_plural': 'Прохождения шагов',
                'unique_together': {('enrollment', 'step')},
            },
        ),
    ]
