# Generated by Django 6.0.3 on 2026-03-18 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='students_company',
        ),
        migrations.AlterModelTable(
            name='course',
            table='courses_course',
        ),
        migrations.AlterModelTable(
            name='coursestep',
            table='courses_coursestep',
        ),
        migrations.AlterModelTable(
            name='enrollment',
            table='courses_enrollment',
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders_order',
        ),
        migrations.AlterModelTable(
            name='person',
            table='students_person',
        ),
        migrations.AlterModelTable(
            name='program',
            table='orders_program',
        ),
        migrations.AlterModelTable(
            name='question',
            table='courses_question',
        ),
        migrations.AlterModelTable(
            name='stepcompletion',
            table='courses_stepcompletion',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users_user',
        ),
    ]
