# Generated by Django 6.0.3 on 2026-03-18 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_company_table_alter_course_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table=None,
        ),
        migrations.AlterModelTable(
            name='course',
            table=None,
        ),
        migrations.AlterModelTable(
            name='coursestep',
            table=None,
        ),
        migrations.AlterModelTable(
            name='enrollment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
        migrations.AlterModelTable(
            name='person',
            table=None,
        ),
        migrations.AlterModelTable(
            name='program',
            table=None,
        ),
        migrations.AlterModelTable(
            name='question',
            table=None,
        ),
        migrations.AlterModelTable(
            name='stepcompletion',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
