# Generated by Django 6.0.3 on 2026-03-18 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_company_table_alter_course_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_type', models.CharField(choices=[('educational', 'Образовательная организация'), ('customer', 'Заказчик'), ('partner', 'Партнер')], max_length=20, verbose_name='Тип организации')),
                ('assigned_for', models.CharField(max_length=200, verbose_name='Для кого (краткое название)')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Кто назначил')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.company', verbose_name='Юридическое лицо')),
            ],
            options={
                'verbose_name': 'Назначение организации',
                'verbose_name_plural': 'Назначения организаций',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'org_type')},
            },
        ),
    ]
