# Generated by Django 6.0.3 on 2026-03-18 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_user_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='courses.company', verbose_name='Текущая организация'),
        ),
    ]
