# Generated by Django 6.0.3 on 2026-03-18 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_user_current_organization'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organizationassignment',
            unique_together=set(),
        ),
    ]
