# Generated by Django 6.0.3 on 2026-03-18 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_person_created_at_person_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_assignments', to='courses.organizationassignment', verbose_name='Назначение организации')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_assignments', to='courses.person', verbose_name='Физическое лицо')),
            ],
            options={
                'verbose_name': 'Связь с организацией',
                'verbose_name_plural': 'Связи с организациями',
                'ordering': ['-created_at'],
                'unique_together': {('person', 'assignment')},
            },
        ),
    ]
