# Generated by Django 6.0.3 on 2026-03-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_space_remove_user_current_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='snils',
            field=models.CharField(blank=True, default='', max_length=14, verbose_name='СНИЛС'),
        ),
    ]
