# Generated by Django 6.0.3 on 2026-03-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_person_snils'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='person',
            name='edu_level',
            field=models.CharField(blank=True, max_length=100, verbose_name='Уровень образования'),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='person',
            name='passport',
            field=models.TextField(blank=True, verbose_name='Паспортные данные'),
        ),
    ]
