# Generated by Django 6.0.3 on 2026-03-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_person_address_person_edu_level_person_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='code',
            field=models.CharField(blank=True, help_text='Используется как пароль для входа в систему', max_length=20, verbose_name='Код доступа'),
        ),
    ]
