# Generated by Django 6.0.3 on 2026-03-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_person_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, verbose_name='Сокращение')),
                ('title', models.TextField(verbose_name='Название программы')),
                ('title_eng', models.TextField(blank=True, verbose_name='Название (англ)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость')),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость текущая')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Подразделение')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категория')),
                ('direction', models.CharField(blank=True, max_length=200, verbose_name='Направление')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='Статус')),
                ('period_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Часов')),
                ('period_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Дней')),
                ('stat_type', models.CharField(blank=True, max_length=50, verbose_name='Тип документа')),
                ('specialty', models.CharField(blank=True, max_length=200, verbose_name='Специальность')),
                ('training_form', models.CharField(blank=True, max_length=100, verbose_name='Форма обучения')),
                ('edu_level', models.CharField(blank=True, max_length=100, verbose_name='Уровень образования')),
                ('prog_group', models.CharField(blank=True, max_length=200, verbose_name='Группа программ')),
                ('is_published', models.BooleanField(default=False, verbose_name='На сайте')),
                ('dvik157', models.BooleanField(default=False, verbose_name='157 ДВИК')),
                ('vmc157', models.BooleanField(default=False, verbose_name='157 ВМК')),
                ('contract_type', models.CharField(blank=True, max_length=100, verbose_name='Тип контракта')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Программа обучения',
                'verbose_name_plural': 'Программы обучения',
                'ordering': ['code'],
            },
        ),
    ]
