# Generated by Django 6.0.3 on 2026-03-28 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название модуля')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.trainingprogram', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Модуль обучения',
                'verbose_name_plural': 'Модули обучения',
                'ordering': ['program', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ModuleStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('type', models.CharField(choices=[('material', 'Изучение материала'), ('practice', 'Практическое занятие'), ('upload', 'Загрузка работы'), ('quiz', 'Промежуточное тестирование'), ('final_exam', 'Итоговая аттестация')], max_length=20, verbose_name='Тип этапа')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='Ссылка на материал')),
                ('exam_config', models.JSONField(blank=True, help_text='{"quiz_step_id": кол-во_вопросов}', null=True, verbose_name='Конфигурация итоговой аттестации')),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Время на тест (мин)')),
                ('pass_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Проходной балл (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='courses.learningmodule', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Этап модуля',
                'verbose_name_plural': 'Этапы модулей',
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('type', models.CharField(choices=[('single', 'Один ответ'), ('multi', 'Несколько ответов'), ('order', 'Последовательность'), ('match', 'Сопоставление')], default='single', max_length=10, verbose_name='Тип')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Баллы')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='URL изображения')),
                ('explanation', models.TextField(blank=True, verbose_name='Пояснение к ответу')),
                ('answers', models.JSONField(help_text='["ответ 1","ответ 2",...]', verbose_name='Варианты ответов')),
                ('correct', models.JSONField(help_text='[0,2]', verbose_name='Правильные ответы')),
                ('terms', models.JSONField(blank=True, null=True, verbose_name='Понятия (для match)')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.modulestep', verbose_name='Этап (тест)')),
            ],
            options={
                'verbose_name': 'Вопрос теста',
                'verbose_name_plural': 'Вопросы тестов',
                'ordering': ['step', 'order'],
            },
        ),
    ]
