# Generated by Django 6.0.3 on 2026-03-28 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_learningmodule_modulestep_quizquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал'),
        ),
        migrations.AddField(
            model_name='order',
            name='payer_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_orders', to='courses.company', verbose_name='Плательщик (организация)'),
        ),
        migrations.AddField(
            model_name='order',
            name='payer_is_person',
            field=models.BooleanField(default=False, verbose_name='Плательщик — сам слушатель'),
        ),
        migrations.AddField(
            model_name='order',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='courses.space', verbose_name='Организация'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Номер договора')),
                ('date', models.DateField(verbose_name='Дата договора')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('our_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='courses.space', verbose_name='Наша организация')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='courses.company', verbose_name='Плательщик')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='courses.contract', verbose_name='Договор'),
        ),
        migrations.CreateModel(
            name='Signer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, verbose_name='ФИО')),
                ('position', models.CharField(max_length=300, verbose_name='Должность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='courses.space', verbose_name='Пространство')),
            ],
            options={
                'verbose_name': 'Подписант',
                'verbose_name_plural': 'Подписанты',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='signer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='courses.signer', verbose_name='Подписант'),
        ),
    ]
