# Generated by Django 6.0.3 on 2026-03-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_order_created_by_order_payer_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulestep',
            name='slide_content',
            field=models.TextField(blank=True, help_text='HTML-код содержимого слайда', verbose_name='HTML-контент слайда'),
        ),
        migrations.AlterField(
            model_name='modulestep',
            name='type',
            field=models.CharField(choices=[('material', 'Изучение материала'), ('practice', 'Практическое занятие'), ('upload', 'Загрузка работы'), ('quiz', 'Промежуточное тестирование'), ('final_exam', 'Итоговая аттестация'), ('slide', 'Слайд (интерактивный)')], max_length=20, verbose_name='Тип этапа'),
        ),
    ]
