# Generated by Django 6.0.3 on 2026-03-28 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_modulestep_slide_content_alter_modulestep_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начат')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершён')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.modulestep', verbose_name='Текущий этап')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.learningmodule', verbose_name='Модуль')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to='courses.person', verbose_name='Слушатель')),
            ],
            options={
                'verbose_name': 'Прогресс по модулю',
                'verbose_name_plural': 'Прогресс по модулям',
                'unique_together': {('person', 'module')},
            },
        ),
        migrations.CreateModel(
            name='StepProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Не начат'), ('in_progress', 'В процессе'), ('completed', 'Завершён'), ('graded', 'Оценён')], default='not_started', max_length=20, verbose_name='Статус')),
                ('score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Балл (%)')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('uploaded_file', models.FileField(blank=True, upload_to='uploads/module_steps/', verbose_name='Загруженный файл')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто оценил')),
                ('module_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_progress', to='courses.moduleprogress', verbose_name='Прогресс модуля')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.modulestep', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Прогресс по этапу',
                'verbose_name_plural': 'Прогресс по этапам',
                'unique_together': {('module_progress', 'step')},
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict, help_text='{"question_id": {"selected": [0,1], "is_correct": true, "points": 2}}', verbose_name='Ответы')),
                ('current_question_index', models.PositiveIntegerField(default=0, verbose_name='Текущий вопрос')),
                ('score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Балл (%)')),
                ('max_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальный балл')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершена')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начата')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена (дата)')),
                ('step_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='courses.stepprogress', verbose_name='Прогресс этапа')),
            ],
            options={
                'verbose_name': 'Попытка теста',
                'verbose_name_plural': 'Попытки тестов',
            },
        ),
    ]
