# Generated by Django 6.0.3 on 2026-03-28 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_moduleprogress_stepprogress_quizattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulestep',
            name='slide_content',
            field=models.TextField(blank=True, help_text='JSON массив слайдов: [{"title":"...","content":"HTML...","quiz":{"question":"...","options":[...],"correct":0,"feedback":"..."}}]', verbose_name='Слайды (JSON)'),
        ),
        migrations.CreateModel(
            name='ModuleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_scores', models.JSONField(default=dict, help_text='{"step_id": 85, "step_id": 92}', verbose_name='Результаты промежуточных аттестаций')),
                ('final_exam_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Балл итоговой (%)')),
                ('final_exam_passed', models.BooleanField(default=False, verbose_name='Итоговая сдана')),
                ('final_exam_details', models.JSONField(default=list, help_text='Полный протокол: вопросы, ответы слушателя, правильные ответы', verbose_name='Детали итоговой аттестации')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завершения')),
                ('is_preview', models.BooleanField(default=False, verbose_name='Режим проверки')),
                ('final_exam_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.modulestep', verbose_name='Этап итоговой аттестации')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='courses.learningmodule', verbose_name='Модуль')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_results', to='courses.person', verbose_name='Слушатель')),
            ],
            options={
                'verbose_name': 'Результат прохождения модуля',
                'verbose_name_plural': 'Результаты прохождения модулей',
                'ordering': ['-completed_at'],
            },
        ),
    ]
