# Generated by Django 6.0.3 on 2026-03-29 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_alter_modulestep_slide_content_moduleresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='programs/docs/%Y/%m/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='courses.trainingprogram', verbose_name='Программа')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто загрузил')),
            ],
            options={
                'verbose_name': 'Документ программы',
                'verbose_name_plural': 'Документы программ',
                'ordering': ['-created_at'],
            },
        ),
    ]
