# Generated by Django 6.0.3 on 2026-03-29 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_programdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramDocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название документа')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Шаблон документа программы',
                'verbose_name_plural': 'Шаблоны документов программ',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='ais_rank',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='АИС ранг'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='ais_sert',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='АИС сертификат'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='ais_uid_doc_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='АИС тип документа'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='archive_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата архивации'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='auto_contract',
            field=models.CharField(blank=True, max_length=255, verbose_name='Авто-контракт'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='blank_reg_type',
            field=models.CharField(blank=True, max_length=10, verbose_name='Тип регистрации бланка'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='blank_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тип бланка'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='bonus_rate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Бонусная ставка'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='color_gr',
            field=models.CharField(blank=True, max_length=50, verbose_name='Цвет группы'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='contract_first',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Первый контракт'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='dpo',
            field=models.CharField(blank=True, max_length=255, verbose_name='ДПО'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата редактирования'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='edu_doc_frdo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Образовательный документ ФРДО'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='eva_default',
            field=models.CharField(blank=True, max_length=50, verbose_name='Оценка по умолчанию'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='examiner_default',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Экзаменатор по умолчанию'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='frdo_doc_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФРДО тип документа'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='frdo_po_prof',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФРДО ПО профессия'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='frdo_po_type_edu',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФРДО ПО тип образования'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='frdo_prog_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФРДО тип программы'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='group_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Лимит группы'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='group_prof',
            field=models.CharField(blank=True, max_length=255, verbose_name='Группа профессии'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='id_blank',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID бланка'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='id_dep',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID подразделения'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='id_org',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID организации'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='id_sign',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID подписанта'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='inspection_sts',
            field=models.CharField(blank=True, max_length=255, verbose_name='Статус инспекции'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='instructor',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID инструктора'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='main_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Основное название'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='msun',
            field=models.FloatField(blank=True, null=True, verbose_name='МСУН'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='new_price_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата изменения цены'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Старая стоимость'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='old_programm',
            field=models.TextField(blank=True, verbose_name='Старая программа'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='online_sts',
            field=models.CharField(blank=True, max_length=255, verbose_name='Статус онлайн'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='period_weeks',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Недель'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='permit_doc_gov',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Разрешительный документ'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='qual_rank_po',
            field=models.CharField(blank=True, max_length=255, verbose_name='Квалификация/разряд ПО'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='quant_required',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Требуемое количество'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='rem_stu',
            field=models.CharField(blank=True, max_length=500, verbose_name='Примечание для слушателя'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='sert_text1',
            field=models.TextField(blank=True, verbose_name='Текст сертификата 1'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='sert_text1_eng',
            field=models.TextField(blank=True, verbose_name='Текст сертификата 1 (англ)'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='sert_text2',
            field=models.TextField(blank=True, verbose_name='Текст сертификата 2'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='sert_text2_eng',
            field=models.TextField(blank=True, verbose_name='Текст сертификата 2 (англ)'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='sert_text3',
            field=models.TextField(blank=True, verbose_name='Текст сертификата 3'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='sert_text3_eng',
            field=models.TextField(blank=True, verbose_name='Текст сертификата 3 (англ)'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='sert_text4',
            field=models.CharField(blank=True, max_length=500, verbose_name='Текст сертификата 4'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='sert_text4_eng',
            field=models.CharField(blank=True, max_length=500, verbose_name='Текст сертификата 4 (англ)'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='sfera_prof',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сфера профессии'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='signing_head',
            field=models.CharField(blank=True, max_length=300, verbose_name='Подписант'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='signing_head_eng',
            field=models.CharField(blank=True, max_length=300, verbose_name='Подписант (англ)'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='sub_prog',
            field=models.CharField(blank=True, max_length=500, verbose_name='Подпрограмма'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='sub_prog_eng',
            field=models.CharField(blank=True, max_length=500, verbose_name='Подпрограмма (англ)'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='tr_form_famrt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Форма обучения ФАМРТ'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='umkd',
            field=models.CharField(blank=True, max_length=255, verbose_name='УМКД'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='user_admin',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID админа'),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость текущая'),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='programdocument',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='courses.programdocumenttemplate', verbose_name='Шаблон'),
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(max_length=500, verbose_name='Пункт справочника')),
                ('usage', models.CharField(help_text='category, direction, department, status, training_form, edu_level, stat_type, blank_type, dpo', max_length=200, verbose_name='Место использования')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Пункт справочника',
                'verbose_name_plural': 'Справочник',
                'ordering': ['usage', 'sort_order', 'entry'],
                'unique_together': {('entry', 'usage')},
            },
        ),
    ]
