# Generated by Django 6.0.3 on 2026-03-29 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_programdocumenttemplate_trainingprogram_ais_rank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Наименование дисциплины/раздела')),
                ('hours', models.IntegerField(default=0, verbose_name='Часов (аудиторных)')),
                ('hours_self', models.FloatField(default=0, verbose_name='Часов (самостоятельных)')),
                ('control_form', models.CharField(blank=True, default='', max_length=100, verbose_name='Форма контроля')),
                ('days', models.IntegerField(blank=True, null=True, verbose_name='Дней')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечание')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='courses.trainingprogram', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Учебный план',
                'verbose_name_plural': 'Учебный план',
                'ordering': ['program', 'sort_order'],
            },
        ),
    ]
