# Generated by Django 6.0.3 on 2026-03-29 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_programplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название подразделения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название роли')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код роли')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Рабочая роль',
                'verbose_name_plural': 'Рабочие роли',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='signer_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_programs', to='courses.person', verbose_name='Подписант'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='department_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='courses.department', verbose_name='Подразделение (справочник)'),
        ),
        migrations.CreateModel(
            name='PersonWorkRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечание')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_roles', to='courses.person', verbose_name='Физлицо')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='courses.workrole', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Назначение роли',
                'verbose_name_plural': 'Назначения ролей',
                'unique_together': {('person', 'role')},
            },
        ),
    ]
