# Generated by Django 6.0.3 on 2026-03-29 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_department_workrole_trainingprogram_signer_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Закреплено'),
        ),
        migrations.CreateModel(
            name='PersonDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название документа')),
                ('doc_type', models.CharField(blank=True, choices=[('spravka', 'Справка'), ('diploma', 'Диплом'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Тип')),
                ('file', models.FileField(blank=True, upload_to='person_docs/%Y/%m/', verbose_name='Файл')),
                ('rotation', models.IntegerField(default=0, verbose_name='Поворот (градусов)')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата архивирования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечание')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_docs', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='courses.person', verbose_name='Слушатель')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_person_docs', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Документ слушателя',
                'verbose_name_plural': 'Документы слушателей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeaService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel_name', models.CharField(max_length=200, verbose_name='Название судна')),
                ('date_from', models.DateField(verbose_name='Дата начала')),
                ('date_to', models.DateField(verbose_name='Дата окончания')),
                ('tonnage', models.IntegerField(default=0, verbose_name='Тоннаж (GT)')),
                ('power', models.IntegerField(default=0, verbose_name='Мощность (кВт)')),
                ('position', models.CharField(blank=True, default='', max_length=200, verbose_name='Должность на судне')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sea_services', to='courses.persondocument', verbose_name='Связанный документ')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sea_services', to='courses.person', verbose_name='Слушатель')),
            ],
            options={
                'verbose_name': 'Плавательный ценз',
                'verbose_name_plural': 'Плавательный ценз',
                'ordering': ['-date_from'],
            },
        ),
    ]
