# Generated by Django 6.0.3 on 2026-03-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_message_is_pinned_persondocument_seaservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='case_status',
            field=models.CharField(blank=True, choices=[('', '—'), ('active', 'В работе'), ('archive', 'Архив')], default='', max_length=20, verbose_name='Статус кейса'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Закреплено (кейс)'),
        ),
    ]
