# Generated by Django 6.0.3 on 2026-03-29 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_message_case_status_alter_message_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ais_position',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Должность АИС диплом'),
        ),
        migrations.AddField(
            model_name='person',
            name='edu_document',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Документ об образовании'),
        ),
        migrations.AddField(
            model_name='person',
            name='edu_reg_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Рег. номер документа об образовании'),
        ),
        migrations.AddField(
            model_name='person',
            name='edu_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год выдачи документа об образовании'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_itf',
            field=models.BooleanField(default=False, verbose_name='Слушатель ИТФ'),
        ),
        migrations.AddField(
            model_name='person',
            name='itf_course',
            field=models.IntegerField(blank=True, null=True, verbose_name='Курс ИТФ'),
        ),
        migrations.AddField(
            model_name='person',
            name='itf_specialty',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Специальность ИТФ'),
        ),
        migrations.CreateModel(
            name='ProgramTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('programs', models.ManyToManyField(blank=True, related_name='templates', to='courses.trainingprogram', verbose_name='Программы')),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.space', verbose_name='Пространство')),
            ],
            options={
                'verbose_name': 'Шаблон набора программ',
                'verbose_name_plural': 'Шаблоны наборов программ',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
