# Generated by Django 6.0.3 on 2026-03-29 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_person_ais_position_person_edu_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='author_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_orders', to='courses.person', verbose_name='Автор (физлицо)'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at_legacy',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Дата создания (Access)'),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='order',
            name='payer_type',
            field=models.CharField(blank=True, choices=[('', '—'), ('fl', 'ФЛ'), ('ul', 'ЮЛ')], default='', max_length=20, verbose_name='Тип плательщика'),
        ),
        migrations.AddField(
            model_name='order',
            name='signed_by_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_orders', to='courses.person', verbose_name='Менеджер подтверждения'),
        ),
        migrations.AddField(
            model_name='order',
            name='signer_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_orders', to='courses.person', verbose_name='Подписант (физлицо)'),
        ),
        migrations.AddField(
            model_name='order',
            name='student_signed_date',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Дата подписания слушателем'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заявки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='courses.person', verbose_name='Слушатель'),
        ),
    ]
