# Generated by Django 6.0.3 on 2026-03-29 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_order_author_person_order_created_at_legacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='blank_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ID бланка'),
        ),
        migrations.AddField(
            model_name='program',
            name='bonus',
            field=models.FloatField(default=0, verbose_name='Бонус'),
        ),
        migrations.AddField(
            model_name='program',
            name='cert_number_endorsement',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='№ серт. андорсмент'),
        ),
        migrations.AddField(
            model_name='program',
            name='cert_number_org',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='№ серт. организации'),
        ),
        migrations.AddField(
            model_name='program',
            name='contract_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Стоимость по договору'),
        ),
        migrations.AddField(
            model_name='program',
            name='cost_net',
            field=models.FloatField(blank=True, null=True, verbose_name='Чистая стоимость'),
        ),
        migrations.AddField(
            model_name='program',
            name='created_at_legacy',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (Access)'),
        ),
        migrations.AddField(
            model_name='program',
            name='created_by_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trainings', to='courses.person', verbose_name='Создал (Person)'),
        ),
        migrations.AddField(
            model_name='program',
            name='department_id_legacy',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID подразделения (Access)'),
        ),
        migrations.AddField(
            model_name='program',
            name='discount_percent',
            field=models.FloatField(default=0, verbose_name='Скидка %'),
        ),
        migrations.AddField(
            model_name='program',
            name='entrance_result',
            field=models.IntegerField(blank=True, null=True, verbose_name='Результат входного контроля'),
        ),
        migrations.AddField(
            model_name='program',
            name='eva_access_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата доступа EVA'),
        ),
        migrations.AddField(
            model_name='program',
            name='eva_access_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eva_trainings', to='courses.person', verbose_name='Менеджер EVA'),
        ),
        migrations.AddField(
            model_name='program',
            name='eval_entrance',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Входная оценка'),
        ),
        migrations.AddField(
            model_name='program',
            name='exam_passed',
            field=models.BooleanField(default=False, verbose_name='Экзамен сдан'),
        ),
        migrations.AddField(
            model_name='program',
            name='exam_result',
            field=models.IntegerField(blank=True, null=True, verbose_name='Результат экзамена'),
        ),
        migrations.AddField(
            model_name='program',
            name='expire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия'),
        ),
        migrations.AddField(
            model_name='program',
            name='first_report_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата первой явки'),
        ),
        migrations.AddField(
            model_name='program',
            name='frdo_confirmed',
            field=models.BooleanField(default=False, verbose_name='ФРДО подтверждено'),
        ),
        migrations.AddField(
            model_name='program',
            name='frdo_status_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата статуса ФРДО'),
        ),
        migrations.AddField(
            model_name='program',
            name='frdo_type',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Тип ФРДО'),
        ),
        migrations.AddField(
            model_name='program',
            name='group_id_legacy',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID группы (Access)'),
        ),
        migrations.AddField(
            model_name='program',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='program',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
        migrations.AddField(
            model_name='program',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи документа'),
        ),
        migrations.AddField(
            model_name='program',
            name='issue_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_trainings', to='courses.person', verbose_name='Менеджер выдачи'),
        ),
        migrations.AddField(
            model_name='program',
            name='issue_type',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Тип выдачи'),
        ),
        migrations.AddField(
            model_name='program',
            name='issued_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата фактической выдачи'),
        ),
        migrations.AddField(
            model_name='program',
            name='learning_here',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Обучается здесь'),
        ),
        migrations.AddField(
            model_name='program',
            name='learning_quality',
            field=models.IntegerField(blank=True, null=True, verbose_name='Качество обучения'),
        ),
        migrations.AddField(
            model_name='program',
            name='learning_status',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Статус обучения'),
        ),
        migrations.AddField(
            model_name='program',
            name='old_bonus',
            field=models.FloatField(blank=True, null=True, verbose_name='Старый бонус'),
        ),
        migrations.AddField(
            model_name='program',
            name='old_discount_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Старая скидка %'),
        ),
        migrations.AddField(
            model_name='program',
            name='original_training_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID оригинальной подготовки'),
        ),
        migrations.AddField(
            model_name='program',
            name='payer_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to='courses.company', verbose_name='Плательщик'),
        ),
        migrations.AddField(
            model_name='program',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AddField(
            model_name='program',
            name='payment_manager',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Менеджер оплаты'),
        ),
        migrations.AddField(
            model_name='program',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to='courses.person', verbose_name='Слушатель'),
        ),
        migrations.AddField(
            model_name='program',
            name='print_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата печати'),
        ),
        migrations.AddField(
            model_name='program',
            name='print_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_trainings', to='courses.person', verbose_name='Менеджер печати'),
        ),
        migrations.AddField(
            model_name='program',
            name='registration_status',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Статус регистрации'),
        ),
        migrations.AddField(
            model_name='program',
            name='report_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата явки'),
        ),
        migrations.AddField(
            model_name='program',
            name='scrap_confirm',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Подтверждение списания'),
        ),
        migrations.AddField(
            model_name='program',
            name='service_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во услуг'),
        ),
        migrations.AddField(
            model_name='program',
            name='step_progress',
            field=models.IntegerField(blank=True, null=True, verbose_name='Прогресс этапов'),
        ),
        migrations.AddField(
            model_name='program',
            name='step_result',
            field=models.IntegerField(blank=True, null=True, verbose_name='Результат этапов'),
        ),
        migrations.AddField(
            model_name='program',
            name='training_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to='courses.trainingprogram', verbose_name='Программа обучения'),
        ),
        migrations.AddField(
            model_name='program',
            name='upd_exam_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ID обновлённого экзамена'),
        ),
        migrations.AlterField(
            model_name='program',
            name='code',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Код/название программы'),
        ),
        migrations.AlterField(
            model_name='program',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='program',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
    ]
