# Generated by Django 6.0.3 on 2026-03-29 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_program_blank_id_program_bonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='courses.order', verbose_name='Заявка'),
        ),
    ]
