# Generated by Django 6.0.3 on 2026-03-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_alter_program_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Ссылка на картинку'),
        ),
    ]
