# Generated by Django 6.0.3 on 2026-03-30 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_quiz_image_url_to_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodule',
            name='cover_image',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Обложка модуля (URL)'),
        ),
        migrations.CreateModel(
            name='ModuleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_modules', to=settings.AUTH_USER_MODEL, verbose_name='Кто выдал')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.learningmodule', verbose_name='Модуль')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_assignments', to='courses.order', verbose_name='Заявка')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_assignments', to='courses.person', verbose_name='Слушатель')),
                ('program_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_assignments', to='courses.program', verbose_name='Строка заявки (подготовка)')),
            ],
            options={
                'verbose_name': 'Назначение модуля',
                'verbose_name_plural': 'Назначения модулей',
                'ordering': ['-assigned_at'],
                'unique_together': {('person', 'module', 'program_line')},
            },
        ),
    ]
