# Generated by Django 6.0.3 on 2026-03-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_module_assignment_and_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.CharField(choices=[('dashboard', 'Дашборд'), ('learning', 'Обучение'), ('schedule', 'График'), ('results', 'Результаты'), ('library', 'Библиотека'), ('programs', 'Программы'), ('modules', 'Модули'), ('persons', 'Слушатели (Физлица)'), ('students', 'Слушатели'), ('companies', 'Юридические лица'), ('organizations', 'Организации'), ('contracts', 'Договоры'), ('orders', 'Заявки')], max_length=50, verbose_name='Пункт меню')),
                ('role', models.CharField(choices=[('student', 'Слушатель'), ('teacher', 'Преподаватель'), ('admin', 'Администратор'), ('superadmin', 'Суперадмин')], max_length=20, verbose_name='Роль')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Видим')),
            ],
            options={
                'verbose_name': 'Настройка меню',
                'verbose_name_plural': 'Настройки меню',
                'ordering': ['menu_item', 'role'],
                'unique_together': {('menu_item', 'role')},
            },
        ),
    ]
