# Generated by Django 6.0.3 on 2026-03-30 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_menu_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(default=list, verbose_name='Ответ слушателя')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильно')),
                ('score', models.FloatField(default=0, verbose_name='Баллы')),
                ('answered_at', models.DateTimeField(auto_now=True, verbose_name='Время ответа')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='courses.person', verbose_name='Слушатель')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_records', to='courses.quizquestion', verbose_name='Вопрос')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='courses.modulestep', verbose_name='Этап (тест)')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
                'unique_together': {('person', 'step', 'question')},
            },
        ),
    ]
