# Generated by Django 6.0.3 on 2026-04-01 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_quiz_answer_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleresult',
            name='completed_steps',
            field=models.PositiveIntegerField(default=0, verbose_name='Пройдено этапов'),
        ),
        migrations.AddField(
            model_name='moduleresult',
            name='correct_questions',
            field=models.PositiveIntegerField(default=0, verbose_name='Правильных ответов'),
        ),
        migrations.AddField(
            model_name='moduleresult',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_results', to='courses.trainingprogram', verbose_name='Программа обучения'),
        ),
        migrations.AddField(
            model_name='moduleresult',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Время прохождения (сек)'),
        ),
        migrations.AddField(
            model_name='moduleresult',
            name='total_questions',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего вопросов в итоговой'),
        ),
        migrations.AddField(
            model_name='moduleresult',
            name='total_steps',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего этапов в модуле'),
        ),
        migrations.AlterField(
            model_name='menupermission',
            name='menu_item',
            field=models.CharField(choices=[('dashboard', 'Дашборд'), ('learning', 'Обучение'), ('programs', 'Программы'), ('organizations', 'Организации'), ('contracts', 'Договоры'), ('students', 'Слушатели'), ('persons', 'Физические лица'), ('modules', 'Модули'), ('companies', 'Юридические лица'), ('menu_settings', 'Настройки меню'), ('impersonate_btn', 'Кнопка «Войти как слушатель»'), ('results', 'Результаты')], max_length=50, verbose_name='Пункт меню'),
        ),
    ]
