# Generated by Django 6.0.3 on 2026-04-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_moduleresult_completed_steps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menupermission',
            name='menu_item',
            field=models.CharField(choices=[('dashboard', 'Дашборд'), ('learning', 'Обучение'), ('programs', 'Программы'), ('organizations', 'Организации'), ('contracts', 'Договоры'), ('students', 'Слушатели'), ('persons', 'Физические лица'), ('modules', 'Модули'), ('companies', 'Юридические лица'), ('menu_settings', 'Настройки меню'), ('impersonate_btn', 'Кнопка «Войти как слушатель»'), ('results', 'Результаты'), ('progress', 'Прогресс')], max_length=50, verbose_name='Пункт меню'),
        ),
    ]
