# Generated by Django 6.0.3 on 2026-04-04 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_alter_menupermission_menu_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleassignment',
            name='manual_grade',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Оценка'),
        ),
    ]
