# Generated by Django 6.0.3 on 2026-04-04 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_moduleassignment_manual_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedModuleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_steps', models.IntegerField(default=0, verbose_name='Всего этапов')),
                ('completed_steps', models.IntegerField(default=0, verbose_name='Пройдено этапов')),
                ('quiz_avg_score', models.FloatField(blank=True, null=True, verbose_name='Ср. балл промежуточных')),
                ('final_score', models.FloatField(blank=True, null=True, verbose_name='Итоговый балл')),
                ('manual_grade', models.CharField(blank=True, default='', max_length=50, verbose_name='Оценка')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('archived_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата архивации')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Архивировал')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.learningmodule', verbose_name='Модуль')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_results', to='courses.person', verbose_name='Слушатель')),
                ('program_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.program', verbose_name='Позиция подготовки')),
                ('training_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.trainingprogram', verbose_name='Программа обучения')),
            ],
            options={
                'verbose_name': 'Архивный результат',
                'verbose_name_plural': 'Архивные результаты',
                'ordering': ['-archived_at'],
            },
        ),
    ]
