# Generated by Django 6.0.3 on 2026-04-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_archivedmoduleresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulestep',
            name='slide_file',
            field=models.FileField(blank=True, null=True, upload_to='slides/', verbose_name='HTML-файл слайдов'),
        ),
    ]
