# Generated by Django 6.0.3 on 2026-04-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_modulestep_slide_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP-адрес')),
                ('description', models.CharField(blank=True, help_text='Например: Офис Владивосток, VPN-сервер', max_length=200, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
            ],
            options={
                'verbose_name': 'Разрешённый IP-адрес',
                'verbose_name_plural': 'Разрешённые IP-адреса',
                'ordering': ['ip_address'],
            },
        ),
        migrations.CreateModel(
            name='RoleIPRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Слушатель'), ('teacher', 'Преподаватель'), ('admin', 'Администратор'), ('superadmin', 'Суперадмин')], max_length=20, unique=True, verbose_name='Роль')),
                ('ip_check_enabled', models.BooleanField(default=False, help_text='Если включено — пользователи с этой ролью смогут войти только с разрешённых IP-адресов', verbose_name='Проверять IP при входе')),
            ],
            options={
                'verbose_name': 'Ограничение IP по роли',
                'verbose_name_plural': 'Ограничения IP по ролям',
                'ordering': ['role'],
            },
        ),
    ]
