# Generated by Django 6.0.3 on 2026-04-05 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_allowedip_roleiprestriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodule',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Обязательные модули учитываются при расчёте прогресса обучения', verbose_name='Обязательный модуль'),
        ),
        migrations.AlterField(
            model_name='menupermission',
            name='menu_item',
            field=models.CharField(choices=[('dashboard', 'Дашборд'), ('learning', 'Обучение'), ('programs', 'Программы'), ('organizations', 'Организации'), ('contracts', 'Договоры'), ('students', 'Слушатели'), ('persons', 'Физические лица'), ('modules', 'Модули'), ('companies', 'Юридические лица'), ('menu_settings', 'Настройки меню'), ('impersonate_btn', 'Кнопка «Войти как слушатель»'), ('results', 'Результаты'), ('progress', 'Прогресс'), ('groups', 'Группы')], max_length=50, verbose_name='Пункт меню'),
        ),
        migrations.CreateModel(
            name='TrainingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('group_number', models.CharField(blank=True, max_length=100, verbose_name='Номер группы')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='Примечания')),
                ('learning_status', models.CharField(blank=True, default='Да', max_length=10, verbose_name='Статус обучения')),
                ('student_limit', models.PositiveIntegerField(default=48, verbose_name='Лимит слушателей')),
                ('elog_status', models.IntegerField(blank=True, null=True, verbose_name='Статус Elog')),
                ('program_name', models.CharField(blank=True, max_length=500, verbose_name='Название программы (Access)')),
                ('rank', models.CharField(blank=True, max_length=200, verbose_name='Звание')),
                ('qual_rank', models.CharField(blank=True, max_length=200, verbose_name='Квалификационное звание')),
                ('qualification', models.CharField(blank=True, max_length=200, verbose_name='Квалификация')),
                ('qual_task', models.CharField(blank=True, max_length=200, verbose_name='Квалификационное задание')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('protocol_number', models.CharField(blank=True, max_length=100, verbose_name='Номер протокола')),
                ('in_low_no', models.CharField(blank=True, max_length=100, verbose_name='Вх. номер')),
                ('out_low_no', models.CharField(blank=True, max_length=100, verbose_name='Исх. номер')),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID из Access (idgr)')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.department', verbose_name='Подразделение')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.company', verbose_name='Организация')),
                ('training_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='courses.trainingprogram', verbose_name='Программа обучения')),
            ],
            options={
                'verbose_name': 'Учебная группа',
                'verbose_name_plural': 'Учебные группы',
                'ordering': ['-date_from'],
            },
        ),
        migrations.AddField(
            model_name='program',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_lines', to='courses.traininggroup', verbose_name='Учебная группа'),
        ),
    ]
